# load("@rules_cc//cc:defs.bzl", "cc_library")
# load("@rules_rust//rust:defs.bzl", "rust_binary")
# load("//tools/bazel:rust_cxx_bridge.bzl", "rust_cxx_bridge")
load("@rules_foreign_cc//foreign_cc:defs.bzl", "cmake")

filegroup(
    name = "unblending_srcs",
    srcs = glob(["include/unblending/unblending/**"]),
    visibility = ["//visibility:public"],
)

cmake(
    name = "unblending",
    lib_source = ":unblending_srcs",
    out_static_libs = ["libunblending.a"],
)

# rust_binary(
#     name = "demo",
#     srcs = glob(["src/**/*.rs"]),
#     edition = "2024",
#     deps = [
#         ":blobstore-sys",
#         ":bridge",
#         "//:cxx",
#     ],
# )

# rust_cxx_bridge(
#     name = "bridge",
#     src = "src/main.rs",
#     deps = [":blobstore-include"],
# )
